// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtttewjtczvoideimwpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dHRld2p0Y3p2b2lkZWltd3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjM0NDksImV4cCI6MjA2NDI5OTQ0OX0.nQrrlBfMYUNtkmiSOze-ix4HBJBGb-3KjpJU1Ro_teY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);